version: '2.3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_tests
    ports:
      - "8086:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - test_net

networks:
  test_net:
    name: jenkins_net

volumes:
  jenkins_home:
    name: jenkins_home