version: '2.3'

services:

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    networks:
      - test_net
    ports:
      - "8888:80"

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    networks:
      - test_net
    volumes:
      - mariadb_data:/bitnami/mariadb
    ports:
      - "3306:3306"

  opencart:
    image: docker.io/bitnami/opencart:3
    container_name: opencart
    ports:
      - "${OPENCART_JENKINS_PORT}:8081"
      - "443:8443"
    environment:
      - OPENCART_HOST=${OPENCART_JENKINS_HOST}:${OPENCART_JENKINS_PORT}
      - APACHE_HTTP_PORT_NUMBER=8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - test_net
    volumes:
      - opencart_data:/bitnami/opencart
      - opencart_storage_data:/bitnami/opencart_storage/
    depends_on:
      - mariadb

networks:
  test_net:
    name: opencart_net

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
